<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I73UVPN" name="Default test" tests="5" failures="1" timestamp="16 Jan 2020 20:28:54 GMT" time="94.171" errors="0">
  <testcase name="ishoverUserOneTest" time="77.699" classname="ie.murph.testautomationu.webdriver_automation.hover.HoverTest">
    <failure type="java.lang.AssertionError" message="Caption is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Caption is not displayed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at ie.murph.testautomationu.webdriver_automation.hover.HoverTest.ishoverUserOneTest(HoverTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ishoverUserOneTest -->
  <testcase name="checkTitleHoverUserOneTest" time="0.047" classname="ie.murph.testautomationu.webdriver_automation.hover.HoverTest"/>
  <testcase name="checkAnchorLinkTextHoverUserOneTest" time="0.053" classname="ie.murph.testautomationu.webdriver_automation.hover.HoverTest"/>
  <testcase name="isAnchorUrlEndsWithHoverUserOneTest" time="0.069" classname="ie.murph.testautomationu.webdriver_automation.hover.HoverTest"/>
  <testcase name="isAnchorUrlContainsHoverUserOneTest" time="0.053" classname="ie.murph.testautomationu.webdriver_automation.hover.HoverTest"/>
</testsuite> <!-- Default test -->
